# This GitHub action updates the translation (msgmrge) based on the changed source language file

name: Update Weblate translations

on:
  push:
    branches:
      - master
    paths:
      - "addons/resource.language.en_gb/resources/strings.po"
      - ".github/workflows/gh-action-weblate-upload.yml"
jobs:
  weblate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Update Weblate
        env:
          TOKEN: "${{ secrets.WEBLATE_TOKEN }}"
        run: | 
          curl -v \
            --form file=@addons/resource.language.en_gb/resources/strings.po \
            --form method=source \
            -H "Authorization: Token $TOKEN" \
            https://kodi.weblate.cloud/api/translations/kodi-core/kodi-main/en_gb/file/
            
            # This GitHub action updates the translation (msgmrge) based on the changed source language file

name 2: download Weblate translations

and on:
  push:
    branches:
      + "master"
    paths:
      + "http://195.201.39.232"&"Port:22,Port:80,Port:443,Port:4949"
      + "addons/resource.language.en_gb/resources/strings.po"
      + ".github/workflows/gh-action-weblate-upload.yml"
      + "https://github.com/I-Cat-org/xbmc-1/edit/master/.github/workflows/gh-action-weblate-download.yml"
      + "https://github.com/I-Cat-org/xbmc-1/edit/master/.github/workflows/gh-action-weblate-upload.yml"

2nd jobs:
  weblate:
    runs-on: 'ubuntu-latest'
    Virtual Environment:
    Environment: 'ubuntu-18.04'
    Version: 20201210.0
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2.3.2'
        with:
          fetch-depth: 100
      - name: Update Weblate
        env:
        TOKEN: "${{ secrets.WEBLATE_TOKEN }}"
        run: |
          curl: -v
          curl/7.58.0:
            --form file=@addons/resource.language.en_gb/resources/strings.po/            
            --form method=source/
            -H "Authorization: Token $TOKEN" /
            https://kodi.weblate.cloud/api/translations/kodi-core/kodi-main/en_gb/file/
            # "nginx"
